title: My first blog
author: Moise Zeleny
theme: minima
email: moiseszeleny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This will be my first blog. I'm going to tlk about physics and python programming.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  moiseszeleny

show_excerpts: true # set to false to remove excerpts on the homepage
